name: TownyBase
version: 0.0.34
website: https://nerotv.live/townybase
api-version: 1.18
description: TownyBase by nerotvlive
author: nerotvlive
main: live.nerotv.Preloader

softdepend:
  - floodgate

depend:
  - Towny
  - Vault
  - ZyneonAPI

loadbefore:
  - GChestShop

commands:
  Balance:
    aliases: [bal,mon,geld,money,munze,munzen,muenze,muenzen,münzen,münze]
  Check: