name: TownyBase
version: '${project.version}'
website: https://nerotv.live/townybase
api-version: 1.19
description: TownyBase by nerotvlive
author: nerotvlive
main: live.nerotv.Preloader

loadbefore:
  - Towny
  - GChestShop

softdepend:
  - floodgate

depend:
  - Vault
  - ZyneonAPI

commands:
  Balance:
    aliases: [bal,mon,geld,money,munze,munzen,muenze,muenzen,münzen,münze]
  Pay: